name = "ANNOUNCEMENT_MODULE"
description = "A Nadybot module to announce messages"
version = "1.0.1"
author = "Nadyita"
github = "Nadybot/ANNOUNCEMENT_MODULE"
bot_type = "Nadybot"
bot_version = "^6.0.0-alpha.1"
